[package]
name = "proton-bindings"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "generate"
path = "src/main.rs"

[dependencies]
proton-ffi = { path = "../proton-ffi" }
interoptopus = { workspace = true }
interoptopus_backend_c = "0.14"
interoptopus_backend_csharp = "0.14"